title: Freeware Projects Hub - Discover and Download Free Software
email: support@wikimint.com
description: >
  Explore a wide range of free software and open-source projects at Freeware Projects Hub. Download, review, and share top-quality free applications for Windows, Mac, Linux, and more. Join our community of developers and tech enthusiasts today!

collections:
  projects:
    output: true
permalink: /:title

disqus:
  shortname: freeware-projects

defaults:
  - scope:
      path: "_projects"
      type: "projects"
    values:
      permalink: /:title
      

remote_theme: wikimint/wmfw
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
