# .github/workflows/deploy.yml
name: Deploy Jekyll site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Use the latest stable version

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build site
        env:
          REMOTE_THEME: ${{ secrets.REMOTE_THEME }}
        run: |
          echo "REMOTE_THEME=$REMOTE_THEME" >> $GITHUB_ENV
          bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
